apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot
        image: tejasdurge55/chatbot-webapp
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "70m"
            memory: "200Mi"
          limits:
            cpu: "100m"
            memory: "250Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
spec:
  selector:
    app: chatbot
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
